# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-18 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printarchive_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='page_date',
            new_name='date_1_page_date',
        ),
        migrations.RenameField(
            model_name='pdf',
            old_name='page_num',
            new_name='date_1_page_num',
        ),
        migrations.AddField(
            model_name='pdf',
            name='date_2_page_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='date_2_page_num',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
