# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-18 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printarchive_app', '0002_auto_20161018_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
    ]
